/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImprimirRecibos.java
 *
 * Created on 23-oct-2012, 19:17:32
 */
package megamar;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author CoLiSa
 */
public class ImprimirRecibos extends javax.swing.JFrame {
    private int idzona;
    
    /** Creates new form ImprimirRecibos */
    public ImprimirRecibos(int idz) {
        initComponents();
        
        idzona = idz;
        this.setLocationRelativeTo(null);
        cargartabla();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbimprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaestadozona = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/printer_48.png"))); // NOI18N
        jbimprimir.setText("Imprimir ");
        jbimprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbimprimir.setEnabled(false);
        jbimprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbimprimir.setIconTextGap(1);
        jbimprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbimprimirActionPerformed(evt);
            }
        });

        tablaestadozona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaestadozona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaestadozonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaestadozona);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1015, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbimprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbimprimirActionPerformed
        /*
         * Cuando se imprime el formulario "Estado de Zona" se registra:
         * numero de recibos cortados, estado de la zona y total a cobrar por el cobrador.
         * Estos datos sirven para calcular luego la liquidacion de los cobradores.
         */
        /*int fila = tablaestadozona.getSelectedRow();
        String idzona = String.valueOf(tablaestadozona.getValueAt(fila, 0));
        String zona = String.valueOf(tablaestadozona.getValueAt(fila, 1));
        String num_recibos = String.valueOf(tablaestadozona.getValueAt(fila, 2));
        String estado_zona = String.valueOf(tablaestadozona.getValueAt(fila, 3));
        String total_cobrar = String.valueOf(tablaestadozona.getValueAt(fila, 4));

        String consulta = "UPDATE zona "
                + "SET num_recibos = '" + num_recibos + "', estado_zona='" + estado_zona + "', total_cobrar='" + total_cobrar + "' "
                + "WHERE idzona='" + idzona + "'";
        try {
            Conectar();
            int done = stmt.executeUpdate(consulta);
            JOptionPane.showMessageDialog(null, "Se actualizaron los datos del estado de la Zona.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            db.close(stmt);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al actualizar los datos del estado de la Zona.", JOptionPane.ERROR_MESSAGE);
        }*/

        try {
            JasperReport reporte = (JasperReport) JRLoader.loadObject("src//reportes//reporterecibos.jasper");
            //JasperReport reporte = JasperCompileManager.compileReport("src//reportes//reporteclientes.jrxml");
            Map parametros = new HashMap();
            parametros.put("pzona", idzona);

            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, db.getMyConnection());
            //JasperViewer.viewReport(print);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Recibo");
            view.setExtendedState(view.MAXIMIZED_BOTH);
            view.setVisible(true);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_jbimprimirActionPerformed

private void tablaestadozonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaestadozonaMouseClicked
        jbimprimir.setEnabled(true);
}//GEN-LAST:event_tablaestadozonaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
/*        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ImprimirRecibos().setVisible(true);
            }
        }); */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbimprimir;
    private javax.swing.JTable tablaestadozona;
    // End of variables declaration//GEN-END:variables
private conexion db;
    private Statement stmt;
    
    public void Conectar() {
        try {
            db = new conexion();      //instancia de la clase conexion.java
            db.init();
            Connection conn = db.getMyConnection();
            stmt = conn.createStatement();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problemas al concetarse a la Base de Datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargartabla() {
        String consulta ="SELECT x.idcliente, x.nombre as 'Nombre', x.apellido as 'Apellido', x.domicilio_comercial as 'Dom. Comercial', x.barrio_comercial as 'Bº Comercial', x.domicilio_particular as 'Dom. Particular', x.barrio_particular as 'Bº Particular', r.descripcion as 'Rubro', x.telefono as 'Telefono', c.compra as 'Compra', c.pagado as 'Pagado', c.saldo as 'Saldo', c.fecha_ultimo_pago as 'Ultimo Pago', c.atraso_total as 'Atraso', c.fecha_cancelacion as 'Cancelacion'"
                + "FROM credito c, cliente x, rubro r, zona z "
                + "WHERE c.estado='DEBE' and c.idcliente=x.idcliente and z.idzona=x.idzona and x.idrubro = r.idrubro and x.idzona = '"+idzona+"' ";
        try {
            Conectar();
            ResultSet rs = stmt.executeQuery(consulta);
            DefaultTableModel modelo = new DefaultTableModel();
            tablaestadozona.setModel(modelo);
            ConversorRSaDefaultTableModel.completar(rs, modelo);
            //codigo para ocultar la primera columna (idplan)
            tablaestadozona.getColumnModel().getColumn(0).setMaxWidth(30);
            tablaestadozona.getColumnModel().getColumn(0).setMinWidth(30);
            tablaestadozona.getColumnModel().getColumn(0).setPreferredWidth(30);
            
            TableColumn sportColumn = tablaestadozona.getColumnModel().getColumn(0);
            //JComboBox comboBox = new JComboBox();
            JCheckBox checkbox = new JCheckBox();
            sportColumn.setCellEditor(new DefaultCellEditor(checkbox));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error al cargar la tabla de Creditos de Clientes.", JOptionPane.ERROR_MESSAGE);
        }
    }

}
